version: '3.8'
services:
  gittest:
    build: ./
  postgres:
    image: postgres
    container_name: postgres-test
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dvdrental
      TZ: "America/Belize"